/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mvhsbandinventory;

/**
 *
 * @author nicholson
 */
public class Display extends javax.swing.JPanel implements java.beans.Customizer
{

    private Object bean;

    /** Creates new customizer DispTest */
    public Display()
    {
        initComponents();
    }

    public void setObject(Object bean)
    {
        this.bean = bean;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        statusTab = new javax.swing.JTabbedPane();
        detailPanel = new javax.swing.JPanel();
        instrumentLabel = new javax.swing.JLabel();
        instruBox = new javax.swing.JTextField();
        brandLabel = new javax.swing.JLabel();
        brandBox = new javax.swing.JTextField();
        serialLabel = new javax.swing.JLabel();
        serialBox = new javax.swing.JTextField();
        rankLabel = new javax.swing.JLabel();
        rankBox = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        valueBox = new javax.swing.JTextField();
        strapLabel = new javax.swing.JLabel();
        strapCombo = new javax.swing.JComboBox();
        ligatureLabel = new javax.swing.JLabel();
        ligCombo = new javax.swing.JComboBox();
        mpieceLabel = new javax.swing.JLabel();
        mpieceCombo = new javax.swing.JComboBox();
        capLabel = new javax.swing.JLabel();
        capCombo = new javax.swing.JComboBox();
        bowLabel = new javax.swing.JLabel();
        bowCombo = new javax.swing.JComboBox();
        noteLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        notesTPane = new javax.swing.JTextPane();
        historyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        searchCombo = new javax.swing.JComboBox();
        searchBar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        instrumentTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        advSearchButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setName(""); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        detailPanel.setLayout(new java.awt.GridBagLayout());

        instrumentLabel.setText("Instrument:");
        instrumentLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(instrumentLabel, gridBagConstraints);

        instruBox.setEditable(false);
        instruBox.setAutoscrolls(false);
        instruBox.setMinimumSize(new java.awt.Dimension(200, 20));
        instruBox.setPreferredSize(null);
        instruBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instruBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(instruBox, gridBagConstraints);

        brandLabel.setText("Brand:");
        brandLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(brandLabel, gridBagConstraints);

        brandBox.setEditable(false);
        brandBox.setAutoscrolls(false);
        brandBox.setMinimumSize(new java.awt.Dimension(200, 20));
        brandBox.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(brandBox, gridBagConstraints);

        serialLabel.setText("Serial Number:");
        serialLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(serialLabel, gridBagConstraints);

        serialBox.setEditable(false);
        serialBox.setAutoscrolls(false);
        serialBox.setMinimumSize(new java.awt.Dimension(200, 20));
        serialBox.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(serialBox, gridBagConstraints);

        rankLabel.setText("Rank:");
        rankLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(rankLabel, gridBagConstraints);

        rankBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rankBox.setText("3");
        rankBox.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(rankBox, gridBagConstraints);

        valueLabel.setText("Value: $");
        valueLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(valueLabel, gridBagConstraints);

        valueBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valueBox.setText("0");
        valueBox.setAutoscrolls(false);
        valueBox.setMinimumSize(new java.awt.Dimension(200, 20));
        valueBox.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(valueBox, gridBagConstraints);

        strapLabel.setText("Neck Strap:");
        strapLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(strapLabel, gridBagConstraints);

        strapCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Yes", "No", "n/a" }));
        strapCombo.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(strapCombo, gridBagConstraints);

        ligatureLabel.setText("Ligature:");
        ligatureLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(ligatureLabel, gridBagConstraints);

        ligCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Yes", "No", "n/a" }));
        ligCombo.setPreferredSize(null);
        ligCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligComboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(ligCombo, gridBagConstraints);

        mpieceLabel.setText("Mouthpiece:");
        mpieceLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(mpieceLabel, gridBagConstraints);

        mpieceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Yes", "No", "n/a" }));
        mpieceCombo.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(mpieceCombo, gridBagConstraints);

        capLabel.setText("Mouthpiece Cap:");
        capLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(capLabel, gridBagConstraints);

        capCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Yes", "No", "n/a" }));
        capCombo.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(capCombo, gridBagConstraints);

        bowLabel.setText("Bow:");
        bowLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        detailPanel.add(bowLabel, gridBagConstraints);

        bowCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Yes", "No", "n/a" }));
        bowCombo.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        detailPanel.add(bowCombo, gridBagConstraints);

        noteLabel.setText("Notes:");
        noteLabel.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        detailPanel.add(noteLabel, gridBagConstraints);

        jScrollPane5.setMinimumSize(new java.awt.Dimension(25, 25));
        jScrollPane5.setPreferredSize(null);

        notesTPane.setMinimumSize(new java.awt.Dimension(25, 25));
        notesTPane.setPreferredSize(null);
        jScrollPane5.setViewportView(notesTPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        detailPanel.add(jScrollPane5, gridBagConstraints);

        statusTab.addTab("Details", detailPanel);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Event"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(100, 64));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout historyPanelLayout = new org.jdesktop.layout.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .add(259, 259, 259))
        );

        statusTab.addTab("History", historyPanel);

        jLabel1.setText("Status:");
        jLabel1.setPreferredSize(null);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(711, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(669, Short.MAX_VALUE))
        );

        statusTab.addTab("Status", jPanel3);

        jPanel1.add(statusTab, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(null);

        saveButton.setText("SAVE CHANGES");
        saveButton.setPreferredSize(null);
        jPanel2.add(saveButton);

        cancelButton.setText("CANCEL CHANGES");
        cancelButton.setPreferredSize(null);
        jPanel2.add(cancelButton);

        deleteButton.setText("DELETE INSTRUMENT");
        deleteButton.setPreferredSize(null);
        jPanel2.add(deleteButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanel1);

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Brand", "Serial #", "Rank", "Value", "Status", "Ligature", "Mouthpiece", "Mouthpiece Cap", "Bow" }));
        searchCombo.setPreferredSize(null);
        searchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboActionPerformed(evt);
            }
        });

        searchBar.setText("Search Bar");
        searchBar.setPreferredSize(null);
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        jScrollPane4.setPreferredSize(null);

        instrumentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Instrument", "Brand", "Serial #"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        instrumentTable.setPreferredSize(null);
        jScrollPane4.setViewportView(instrumentTable);

        searchButton.setText("Search");
        searchButton.setPreferredSize(null);

        addButton.setText("Add New Instrument");
        addButton.setPreferredSize(null);

        advSearchButton.setText("ADVANCED SEARCH");
        advSearchButton.setPreferredSize(null);

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .add(jPanel8Layout.createSequentialGroup()
                        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(addButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(searchBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel8Layout.createSequentialGroup()
                                .add(searchCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(searchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(advSearchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(searchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(searchCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(advSearchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel8);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchComboActionPerformed
    {//GEN-HEADEREND:event_searchComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_searchComboActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchBarActionPerformed
    {//GEN-HEADEREND:event_searchBarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_searchBarActionPerformed

    private void instruBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_instruBoxActionPerformed
    {//GEN-HEADEREND:event_instruBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_instruBoxActionPerformed

    private void ligComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ligComboActionPerformed
    {//GEN-HEADEREND:event_ligComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ligComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton advSearchButton;
    private javax.swing.JComboBox bowCombo;
    private javax.swing.JLabel bowLabel;
    private javax.swing.JTextField brandBox;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox capCombo;
    private javax.swing.JLabel capLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JTextField instruBox;
    private javax.swing.JLabel instrumentLabel;
    private javax.swing.JTable instrumentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox ligCombo;
    private javax.swing.JLabel ligatureLabel;
    private javax.swing.JComboBox mpieceCombo;
    private javax.swing.JLabel mpieceLabel;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextPane notesTPane;
    private javax.swing.JTextField rankBox;
    private javax.swing.JLabel rankLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox searchCombo;
    private javax.swing.JTextField serialBox;
    private javax.swing.JLabel serialLabel;
    private javax.swing.JTabbedPane statusTab;
    private javax.swing.JComboBox strapCombo;
    private javax.swing.JLabel strapLabel;
    private javax.swing.JTextField valueBox;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
